### ISSUE TITLE
执行一键标注报错！

### ISSUE THREAD

**Issue by yh7109** [CLUEbenchmark/modelfun#1]
![image](https://user-images.githubusercontent.com/36106408/188048402-f22bc8ab-75b8-425c-b349-d47d132e87cb.png)

**Comment by yh7109** [comment]
数据用的下载好的Excel模板数据，原封不动的重新上传的

**Comment by brightmart** [comment]
输入一下命令：nvidia-smi，看看有什么反馈？ 这个是需要GPU环境的。
https://github.com/wookayin/gpustat/issues/90
