### ISSUE TITLE
请问小样本算法、提示学习算法、全能模型GPT3相关问题

### ISSUE THREAD

**Issue by luoqishuai** [CLUEbenchmark/modelfun#2]
徐老师：
　　您好：
　　我看产品页面和开源项目有一些区别，想和您咨询一下。
　　1.其中关于代码中的小样本算法和提示学习算法请问您是如何应用的呢？好像和产品页面上的那几个模型对不上，是在什么时间、条件下使用呢？
　　2.还有看到全能模型（GPT3）是使用openai进行管理，因为已经由外部系统进行管理，那么模型训练和推理在代码中不可见，请问该模型是怎么训练和推理的呢？（譬如是否有用到标签信息....）

**Comment by brightmart** [comment]
感谢提问。
@mrbeann  帮忙解答一下

**Comment by mrbeann** [comment]
感谢您的提问，很高兴您对这个项目感兴趣
1. 小样本和提示学习部分这里是基于paddlepaddle实现的，具体你可以看algorithm/paddle_backend/paddlecls 部分的代码
2. GPT-3由于是闭源系统，并且涉及收费（OpenAI收费）所以在开源系统中我们保留了接口但是没有采用（推荐你可以看我们的新项目[CLUEAI](https://github.com/clue-ai/clueai-python)）。具体你可以看[openai的文档](https://beta.openai.com/docs/introduction)。它需要提供标签，并且也可以支持提供一定的示例样本

**Comment by luoqishuai** [comment]
> 感谢您的提问，很高兴您对这个项目感兴趣
> 
> 1. 小样本和提示学习部分这里是基于paddlepaddle实现的，具体你可以看algorithm/paddle_backend/paddlecls 部分的代码
> 2. GPT-3由于是闭源系统，并且涉及收费（OpenAI收费）所以在开源系统中我们保留了接口但是没有采用（推荐你可以看我们的新项目[CLUEAI](https://github.com/clue-ai/clueai-python)）。具体你可以看[openai的文档](https://beta.openai.com/docs/introduction)。它需要提供标签，并且也可以支持提供一定的示例样本

　　谢谢大佬们的开源和回复，该项目对我启发很多，也GET了GPT3的相关知识。

　　产品页面的内容分析模型，是在用户在产品页面点击“内容分析模型”，用户提供示例样本和标签，点击保存后，开始调用相关算法-使用paddle.Taskflow进行相似度检测....
　　“内容分析”相关算法从开始到结束的环节都很明确。

　　小样本和提示学习部分这里我看到了你们的实现方案。但是我没有找到，谁来调用、什么条件下调用，所以有些困惑。

**Comment by mrbeann** [comment]
> > 感谢您的提问，很高兴您对这个项目感兴趣
> > 
> > 1. 小样本和提示学习部分这里是基于paddlepaddle实现的，具体你可以看algorithm/paddle_backend/paddlecls 部分的代码
> > 2. GPT-3由于是闭源系统，并且涉及收费（OpenAI收费）所以在开源系统中我们保留了接口但是没有采用（推荐你可以看我们的新项目[CLUEAI](https://github.com/clue-ai/clueai-python)）。具体你可以看[openai的文档](https://beta.openai.com/docs/introduction)。它需要提供标签，并且也可以支持提供一定的示例样本
> 
> 　　谢谢大佬们的开源和回复，该项目对我启发很多，也GET了GPT3的相关知识。
> 
> 　　产品页面的内容分析模型，是在用户在产品页面点击“内容分析模型”，用户提供示例样本和标签，点击保存后，开始调用相关算法-使用paddle.Taskflow进行相似度检测.... 　　“内容分析”相关算法从开始到结束的环节都很明确。
> 
> 　　小样本和提示学习部分这里我看到了你们的实现方案。但是我没有找到，谁来调用、什么条件下调用，所以有些困惑。

这部分对应于ptunning算法，你可以看我上面提到的那个文件夹下的算法。调用在提供训练样本的情况下会默认执行这个。所以从用户界面没有显示调用

**Comment by luoqishuai** [comment]
> > > 感谢您的提问，很高兴您对这个项目感兴趣
> > > 
> > > 1. 小样本和提示学习部分这里是基于paddlepaddle实现的，具体你可以看algorithm/paddle_backend/paddlecls 部分的代码
> > > 2. GPT-3由于是闭源系统，并且涉及收费（OpenAI收费）所以在开源系统中我们保留了接口但是没有采用（推荐你可以看我们的新项目[CLUEAI](https://github.com/clue-ai/clueai-python)）。具体你可以看[openai的文档](https://beta.openai.com/docs/introduction)。它需要提供标签，并且也可以支持提供一定的示例样本
> > 
> > 
> > 　　谢谢大佬们的开源和回复，该项目对我启发很多，也GET了GPT3的相关知识。
> > 　　产品页面的内容分析模型，是在用户在产品页面点击“内容分析模型”，用户提供示例样本和标签，点击保存后，开始调用相关算法-使用paddle.Taskflow进行相似度检测.... 　　“内容分析”相关算法从开始到结束的环节都很明确。
> > 　　小样本和提示学习部分这里我看到了你们的实现方案。但是我没有找到，谁来调用、什么条件下调用，所以有些困惑。
> 
> 这部分对应于ptunning算法，你可以看我上面提到的那个文件夹下的算法。调用在提供训练样本的情况下会默认执行这个。所以从用户界面没有显示调用

嗯嗯，明白了，多谢大佬解答。
